import { ApiProperty } from '@nestjs/swagger';
import { Build, TestRun, TestStatus } from '@prisma/client';
import { BuildDto } from './build.dto';

describe('BuildDto', () => {
  it.each([
    [
      'undefined testRuns',
      {
        id: 'a9385fc1-884d-4f9f-915e-40da0e7773d5',
        number: null,
        branchName: 'develop',
        status: null,
        projectId: 'e0a37894-6f29-478d-b13e-6182fecc715e',
        updatedAt: new Date(),
        createdAt: new Date(),
        userId: null,
        testRuns: undefined,
      },
    ],
    [
      'empty testRuns',
      {
        id: 'a9385fc1-884d-4f9f-915e-40da0e7773d5',
        number: null,
        branchName: 'develop',
        status: null,
        projectId: 'e0a37894-6f29-478d-b13e-6182fecc715e',
        updatedAt: new Date(),
        createdAt: new Date(),
        userId: null,
        testRuns: [],
      },
    ],
  ])('new with %s', (_, build) => {
    const buildDto: BuildDto = {
      id: build.id,
      number: build.number,
      branchName: build.branchName,
      status: 'new',
      projectId: build.projectId,
      updatedAt: build.updatedAt,
      createdAt: build.createdAt,
      userId: null,
      passedCount: 0,
      unresolvedCount: 0,
      failedCount: 0,
    };

    const result = new BuildDto(build);

    expect(result).toEqual(buildDto);
  });

  it('passed', () => {
    const build: Build & {
      testRuns: TestRun[];
    } = {
      id: 'a9385fc1-884d-4f9f-915e-40da0e7773d5',
      number: null,
      branchName: 'develop',
      status: null,
      projectId: 'e0a37894-6f29-478d-b13e-6182fecc715e',
      updatedAt: new Date(),
      createdAt: new Date(),
      userId: null,
      testRuns: [
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.ok,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment1',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.approved,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment2',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
      ],
    };
    const buildDto: BuildDto = {
      id: build.id,
      number: build.number,
      branchName: build.branchName,
      status: 'passed',
      projectId: build.projectId,
      updatedAt: build.updatedAt,
      createdAt: build.createdAt,
      userId: null,
      passedCount: 2,
      unresolvedCount: 0,
      failedCount: 0,
    };

    const result = new BuildDto(build);

    expect(result).toEqual(buildDto);
  });

  it('failed', () => {
    const build: Build & { testRuns: TestRun[] } = {
      id: 'a9385fc1-884d-4f9f-915e-40da0e7773d5',
      number: null,
      branchName: 'develop',
      status: null,
      projectId: 'e0a37894-6f29-478d-b13e-6182fecc715e',
      updatedAt: new Date(),
      createdAt: new Date(),
      userId: null,
      testRuns: [
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.ok,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.approved,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment1',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.failed,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment2',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
      ],
    };
    const buildDto: BuildDto = {
      id: build.id,
      number: build.number,
      branchName: build.branchName,
      status: 'failed',
      projectId: build.projectId,
      updatedAt: build.updatedAt,
      createdAt: build.createdAt,
      userId: null,
      passedCount: 2,
      unresolvedCount: 0,
      failedCount: 1,
    };

    const result = new BuildDto(build);

    expect(result).toEqual(buildDto);
  });

  it('unresolved', () => {
    const build: Build & { testRuns: TestRun[] } = {
      id: 'a9385fc1-884d-4f9f-915e-40da0e7773d5',
      number: null,
      branchName: 'develop',
      status: null,
      projectId: 'e0a37894-6f29-478d-b13e-6182fecc715e',
      updatedAt: new Date(),
      createdAt: new Date(),
      userId: null,
      testRuns: [
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.ok,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment1',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.approved,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment2',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.failed,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: null,
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.new,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
        {
          id: '10fb5e02-64e0-4cf5-9f17-c00ab3c96658',
          imageName: '1592423768112.screenshot.png',
          diffName: null,
          diffPercent: null,
          diffTollerancePercent: 1,
          pixelMisMatchCount: null,
          status: TestStatus.unresolved,
          buildId: '146e7a8d-89f0-4565-aa2c-e61efabb0afd',
          testVariationId: '3bc4a5bc-006e-4d43-8e4e-eaa132627fca',
          updatedAt: new Date(),
          createdAt: new Date(),
          name: 'ss2f77',
          browser: 'chromium',
          device: null,
          os: null,
          viewport: '1800x1600',
          baselineName: null,
          ignoreAreas: '[]',
          comment: 'some comment',
          branchName: 'develop',
          baselineBranchName: 'master',
        },
      ],
    };
    const buildDto: BuildDto = {
      id: build.id,
      number: build.number,
      branchName: build.branchName,
      status: 'unresolved',
      projectId: build.projectId,
      updatedAt: build.updatedAt,
      createdAt: build.createdAt,
      userId: null,
      passedCount: 2,
      unresolvedCount: 2,
      failedCount: 1,
    };

    const result = new BuildDto(build);

    expect(result).toEqual(buildDto);
  });
});
