name: CI

on: [push]

jobs:
  build:
    # https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14.16.1'

      - name: Install npm dependencies
        run: npm ci

      - name: Prisma generate
        run: npm run prisma:generate

      - name: Unit tests
        run: npm run test:cov

      - name: Build and run containers
        run: docker-compose up --build -d

      # FIXME: This action is unmaintained.
      - name: Wait untill service started (replace with health status check)
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: '10s'

      - name: Run acceptance tests
        run: npm run test:acceptance

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Stop containers
        if: always()
        run: docker-compose down

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
