# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install npm dependencies
      run: npm ci
      
    - name: Unit tests
      run: npm run test
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: vrt_db_dev
        postgresql user: postgres
        postgresql password: postgres
        
    - name: Wait untill DB started (workaround of https://github.com/Harmon758/postgresql-action/issues/7)
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '10s'
      
    - name: Apply DB migrations
      run: npx prisma migrate up -c --experimental
    
    - name: Run e2e tests
      run: npm run test:e2e
